options {
    directory "/var/cache/bind";
    listen-on { any; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
    dnssec-validation no;
};

zone "acme-fake.local" IN {
    type master;
    file "/etc/bind/zones/db.acme-fake.local";
    allow-transfer { none; };
};
