server {
    listen 80 default_server;
    server_name acme-fake.local www.acme-fake.local;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        add_header X-Acme-CMS "1.4.2" always;
    }
}
